name: Deploy to Exoscale VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}        # VM IP or hostname (store in GitHub secrets)
          username: ${{ secrets.VM_USER }}    # VM username (e.g., root or ubuntu)
          key: ${{ secrets.VM_SSH_KEY }}      # Private SSH key from secret
          script: |
            cd inenp_ibm_webapp || exit 1
            git pull
            docker build -t inenp_webapp:latest .
            docker stop inenp_webapp || true
            docker rm inenp_webapp || true
            docker run -d --name inenp_webapp -p 80:80 inenp_webapp:latest
